ppw2020/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story.urls'))
]

story/urls.py
from django.urls import path, include
from . import views

app_name = "story"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name='about'),
    path("course/", views.show_course, name='course'),
    path("course/create/", views.create_course, name='create_course'),
    path("course/delete/<int:matkul_pk>/", views.delete_course, name='delete_course'),
    path("course/details/<int:matkul_pk>/", views.course_details, name='course_details'),

    path("activity/", views.activity, name="activity"),
    path("activity/create/", views.create_activity, name="create_activity"),
    path("activity/<int:activity_id>/add_member", views.add_member, name="add_member"),
    path("activity/remove/member/<int:member_id>", views.kick_member, name="kick_member"),
    path("activity/remove/<int:activity_id>", views.remove_activity, name="remove_activity"),

    path("accordion/", views.accordion, name="accordion"),

    path("book/", views.book, name="book"),
    path("dataBook/", views.dataBook, name="dataBook"),

    path("login/", views.login_view, name="login"),
    path("register/", views.signup_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.profile_view, name="dashboard"),
]

story/models.py
from django.db import models


# Create your models here.


class Course(models.Model):
    nama_mata_kuliah = models.CharField(max_length=200)
    dosen_pengajar = models.CharField(max_length=200)
    jumlah_sks = models.PositiveSmallIntegerField()
    deskripsi_mata_kuliah = models.TextField()
    semester = models.CharField(max_length=200)
    tahun_ajaran = models.CharField(max_length=200)
    ruang_kelas = models.CharField(max_length=200)

    def __str__(self):
        return self.nama_mata_kuliah


class Activity(models.Model):
    title = models.CharField(max_length=50, blank=False)
    description = models.CharField(max_length=100, blank=False)
    
    def __str__(self):
        return self.title


class Member(models.Model):
    name = models.CharField(max_length=50, blank=False)
    activity = models.ForeignKey(
        Activity,
        related_name="members",
        blank=False,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Account(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=150, null=True)
	email = models.EmailField(max_length=200, null=True)
	hobby = models.CharField(max_length=50, null=True)
	image = models.TextField(default='/static/story/logo/user.svg', null=True, blank=True)
	profilepicture = models.ImageField(default='user.svg', null=True, blank=True)

	def __str__(self):
		return self.user.username

story/forms.py
from django import forms
from .models import *

SEMESTER = [
    ('gasal', 'Gasal'),
    ('genap', 'Genap'),
]
TAHUN = [
    ('2020/2021', '2020/2021'),
    ('2021/2022', '2021/2022'),
    ('2022/2023', '2022/2023'),
]


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
    text_area = {
        'class': "form__control",
        'cols': 90,
        'rows': 5,
        'required': 'required'
    }
    deskripsi_mata_kuliah = forms.CharField(
        widget=forms.Textarea(attrs=text_area))
    semester = forms.ChoiceField(choices=SEMESTER)
    tahun_ajaran = forms.ChoiceField(choices=TAHUN)


class CreateActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        labels = {
            'title':'Nama Kegiatan',
            'description': 'Deskripsi kegiatan'
        }
        help_texts = {
            'title': '*max 50 characters',
            'description': '*max 100 characters'
        }

class AddMemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['name']
        labels = {
            'name':'Nama kamu?'
        }
        help_texts = {
            'name': '*max 50 characters',
        }

from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Account

class SignupForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		fields = UserCreationForm.Meta.fields + ("email",)
		labels = {
			'email': 'Email',
		}

class AccountForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = ['hobby']

class ProfileSettingsForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = '__all__'
		exclude = ['user', 'image']

story/views.py
from django.http import request
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from . import forms
from .models import *


from django.http import JsonResponse
import json
import requests

# Create your views here.
def home(request):
    return render(request, 'story/story1.html')

def about(request):
    return render(request, 'story/story3.html')

def create_course(request):
    form = forms.CourseForm(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        form.save()
        return redirect('story:course')

    context = {
        "form":form
    }
    return render(request, 'story/create_course.html', context)

def show_course(request):
    matkuls = Course.objects.all().order_by('nama_mata_kuliah')
    context = {
        'matkuls':matkuls
    }
    return render(request, 'story/show_course.html', context)
def course_details(request, matkul_pk):
    matkul = Course.objects.get(id=matkul_pk)
    context = {
        'matkul':matkul
    }
    return render(request, 'story/course_details.html', context)
def delete_course(request, matkul_pk):
    matkul = Course.objects.get(id=matkul_pk)
    matkul.delete()
    return redirect('story:course')

def activity(request):
    activities = Activity.objects.all()
    context = {
        'activities': activities,
    }
    return render(request, 'story/activity.html', context)

def create_activity(request):
    form = forms.CreateActivityForm(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        form.save()
        return redirect('story:activity')
    context = {
        "form":form
    }
    return render(request, 'story/create_activity.html', context)

def remove_activity(request, activity_id):
    obj = Activity.objects.get(id=activity_id)
    obj.delete()
    return redirect('story:activity')

def add_member(request, activity_id):
    activ = Activity.objects.get(id=activity_id)
    form = forms.AddMemberForm(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        instance = form.save(commit=False)
        instance.activity = activ
        instance.save()
        return redirect('story:activity')
    context = {
        "form":form,
        'activity': activ
    }
    return render(request, 'story/add_member.html', context)

def kick_member(request, member_id):
    member = Member.objects.get(id=member_id)
    member.delete()
    return redirect('story:activity')

def accordion(request):
    return render(request, 'story/accordion.html')

def book(request):
    return render(request, 'story/book.html')

def dataBook(request):
    q = request.GET.get('q') or 'a'
    api = requests.get('https://www.googleapis.com/books/v1/volumes?q='+q).content
    responseData = json.loads(api)
    return JsonResponse(responseData, safe=False)

from .forms import SignupForm, AccountForm, ProfileSettingsForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
import os
import base64
from ppw2020.settings import MEDIA_ROOT
from django.contrib import messages
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        account_form = AccountForm(request.POST)
        if form.is_valid() and account_form.is_valid():
            user = form.save()
            account = account_form.save(commit=False)
            account.user = user
            account.name = user.username
            account.email = user.email
            account.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('story:dashboard')
    else:
        form = SignupForm()
        account_form = AccountForm()

    context = {'form': form, 'account_form': account_form}
    return render(request, 'story/register.html', context)


@login_required(login_url='/login')
def logout_view(request):
    logout(request)
    return redirect('story:about')


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('story:dashboard')
        else:
            messages.info(request, 'Username OR password is incorrect')
    context = {}
    return render(request, 'story/login.html', context)


@login_required(login_url='/login')
# @allowed_users(allowed_roles=['account'])
def profile_view(request):
    account = request.user.account
    form = ProfileSettingsForm(instance=account)

    if request.method == 'POST':
        form = ProfileSettingsForm(
            request.POST, request.FILES, instance=account)
        if form.is_valid():
            ins = form.save()
            if request.FILES.get('profilepicture'):
                file_path = os.path.join(MEDIA_ROOT, str(request.FILES.get('profilepicture')))
                with open(file_path, "rb") as img_file:
                    my_string = "data:image/png;base64,"+str(base64.b64encode(img_file.read()).decode('utf-8'))
                ins.image = my_string
                ins.save()
                messages.warning(request, 'Your profile picture so cool!😎')
            elif request.POST.get('profilepicture-clear') != None:
                ins.image = '/static/story/logo/user.svg'
                ins.save()
                messages.warning(request, 'Your profile picture so ugly!😈')
            else:
                messages.warning(request, 'Profile updated successfully!😊')
            
    context = {'form': form, 'account': account}
    return render(request, 'story/dashboard.html', context)

story/templates/story/accordion.html
{% extends 'story/base.html' %}
{% load static %}


{% block head %}
<link rel="stylesheet" href={% static 'story/story3.css' %}>

{% endblock head %}


{% block title %}
<title>Altop | accordion</title>
{% endblock title %}


{% block body %}
<div id="accordion" class="dark">
  <h2 class="title__st3" style="width: fit-content; margin: auto;">accordion ah mantap</h2>
  <ul style="padding: 10px;" class="container accordion">
    <li>
      <div class="toggle" href=#>
        <span id="accordion-1">pengalaman organisasi/kepanitiaan</span> 

        <div>
          <a class="button-up">👆</a>
          <a class="button-down">👇</a>
        </div>

      </div>

      <p class="inner">
        banyak dah sibuk takut gamuat 😎
      </p>
    </li>

    <li>
      <div class="toggle" href=#>
        <span id="accordion-2">Prestasi</span> 
        <div>
          <a class="button-up">👆</a>
          <a class="button-down">👇</a>
        </div>
      </div>
      <p class="inner">
        berat badan turun 5kg dalam seminggu 🏆🥇
      </p>
    </li>

    <li>
      <div class="toggle" href=#>
        <span id="accordion-3">film favorit</span> 
        <div>
          <a class="button-up">👆</a>
          <a class="button-down">👇</a>
        </div>
      </div>
      <p class="inner">
        the mortal instrument, iron fist, dll. 🎬🎥🍿
      </p>
    </li>

    <li>
      <div class="toggle" href=#>
        <span id="accordion-4">aktivitas saat ini</span> 
        <div>
          <a class="button-up">👆</a>
          <a class="button-down">👇</a>
        </div>
      </div>
      <p class="inner">
        nonton drakor lahh ga sabar liburan 🎊
      </p>
    </li>
  </ul>
</div>
{% endblock body %}


{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
  
    $('.toggle span').click(function (e) {
      let $this = $(this).parent();

      if ($this.next().hasClass('show')) {
        $this.next().removeClass('show');
        $this.next().slideUp(350);
      } else {
        $this.parent().parent().find('li .inner').removeClass('show');
        $this.parent().parent().find('li .inner').slideUp(350);
        $this.next().toggleClass('show');
        $this.next().slideToggle(350);
      }
    });

    $('.button-up').click(function () {
      var accordion = $(this).parent().parent().parent();

      if (!accordion.is(':first-child')) {
        accordion.insertBefore(accordion.prev());
      } 
    })

    $('.button-down').click(function () {
      var accordion = $(this).parent().parent().parent();

      if (!accordion.is(':last-child')) {
        accordion.insertAfter(accordion.next());
      } 
    })
  
</script>
{% endblock script %}

story/templates/story/activity.html
{% extends 'story/base.html' %}
{% load static %}


{% block head %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href={% static 'story/activity.css' %}>
{% endblock head %}


{% block title %}
<title>Altop | Activity</title>
{% endblock title %}


{% block body %}
<div class="activity">
  <div class="head__wrapper">
    <h1>Activities</h1>
    <code>Join me do some activities by putting your name on the list(s).</code>
    <a href={% url 'story:create_activity' %} class="add__btn">Add an Activity</a>
  </div>
  <div class="card__wrapper row">
    {% for activity in activities %}
    <div class="activity__card col-lg-4 col-md-6">
      <div class="card">
        <div class="card-header">
          <h4>{{activity.title|title}}</h4>
          <a href={% url 'story:remove_activity' activity.id %}><i class="material-icons">close</i></a>
        </div>
        <div class="card-body">
          <h5>{{activity.description}}</h5>
          {% if activity.members.all.count > 0 %}
          <p style="text-align: left;">Participants:</p>
          <ul>
            {% for member in activity.members.all %}
            <li style="text-align: left; position: relative;"><p style="display: inline-block;">{{member}}</p> <a style="color: rgb(255, 41, 41); position: absolute; right: 10px;" href={% url 'story:kick_member' member.id %}>kick!!</a></li>
            {% endfor %}
          </ul>
          {% endif %}
          <a href={% url 'story:add_member' activity.id %}>
            <div class="btn btn__activity"><code>I want to join</code></div>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>


</div>
{% endblock body %}


{% block script %}

{% endblock script %}

story/templates/story/add_member.html
{% extends 'story/activity.html' %}
{% load static %}


{% block head %}
  <link rel="stylesheet" href={% static 'story/create_activity.css' %}>
{% endblock head %}


{% block body %}
<div class="create__activity">
  <form autocomplete="off" class="form" action={% url 'story:add_member' activity.id %} method="POST">
    <h2 class="title__activity">Join me on {{activity.title | title}}</h2>
    <h4><code>*{{activity.description}}*</code></h4>
    {% csrf_token %}
    {{ form.as_p }}
    
      <button class="btn" type="submit" name="action">
        Add
      </button>
    
    
  </form>
</div>
{% endblock body %}
  

story/templates/story/create_activity.html
{% extends 'story/activity.html' %}
{% load static %}


{% block head %}
<link rel="stylesheet" href={% static 'story/create_activity.css' %}>
{% endblock head %}


{% block body %}
<div class="create__activity">
  <form autocomplete="off" class="form" action={% url 'story:create_activity' %} method="POST">
    <h2 class="title__activity">Create an Activity</h2>
    
    {% csrf_token %}
    {{ form.as_p }}
    
      <button class="btn" type="submit" name="action">
        Add
      </button>
    
    
  </form>
</div>
{% endblock body %}
  
  

story/templates/story/create_course.html
{% extends 'story/base.html' %}
{% load static %}

<!-- HEAD -->
{% block head %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://kit.fontawesome.com/f0cf88c973.js" crossorigin="anonymous"></script>
<link
href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:100,200,300,400|Raleway:400,800|Indie+Flower|Ubuntu:400,500,600,300&display=swap"
rel="stylesheet">
<link rel="stylesheet" href={% static 'story/create_course.css' %}>
{% endblock head %}

{% block title %}
<title>Altop | Course</title>
{% endblock title %}


{% block body %}
  <div class="create__courses">
    <form autocomplete="off" class="form" action={% url 'story:create_course' %} method="POST">
      <h2 class="title__course">Tambah Mata Kuliah</h2>
      <hr>
      {% csrf_token %}
      {{ form.as_p }}
      <div style="text-align: left; margin-top: 30px;">
        <button class="btn btn-large waves-effect waves-light" type="submit" name="action">
          Submit
          <i class="material-icons right">send</i>
        </button>
      </div>
      
    </form>
  </div>
{% endblock body %}


{% block script %}
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
{% endblock script %}
  
  

story/templates/story/dashboard.html
{% extends 'story/base.html' %}
{% load static %}

<!-- HEAD -->
{% block head %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://kit.fontawesome.com/f0cf88c973.js" crossorigin="anonymous"></script>
<link
  href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:100,200,300,400|Raleway:400,800|Indie+Flower|Ubuntu:400,500,600,300&display=swap"
  rel="stylesheet">
  <link rel="stylesheet" href={% static 'story/story3.css' %}>
  <link rel="stylesheet" href={% static 'story/profile.css' %}>
{% endblock head %}

{% block title %}
<title>{{request.user.account.name}}'s Dashboard</title>
{% endblock title %}


{% block body %}
<div class="dark">
  <div class="container profile__padd">

    <div class="row">
      <div class="col l3 s12">
        <div style="text-align: center; padding: 0 0 20px;" class="card shadow card-body">
          <a class="btn waves-effect waves-light" href="{% url 'story:home' %}" style="
          background: white;
          color: #4c495c;
          border-radius: 15px 15px 0 0;
          margin-bottom: 10px;
          background: #4df3b9;
          ">
              &#8592; Back to 🏠
          </a>
          <h5 class="title__st3" style="width: fit-content; margin: auto auto 20px;">Edit Profile</h2>

          <img class="profile-pic" src="{{request.user.account.image}}">


        </div>
      </div>
      <div class="col l9 s12">
        <div style="padding: 10px;" class="card shadow card-body">
          <form class="profileset" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            {% for message in messages %}
            <div class="z-depth-1" style="padding: 6px;
            font-size: .8rem;
            margin: auto;
            color: #ffffff; 
            height: fit-content; 
            border-radius: 5px; 
            width: fit-content;
            background: transparent">
              {{message}}
            </div>
            {% endfor %}
            <button class="reg__btn" type="submit" name="action"
              style="border-radius: 5px;">
              Submit
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}


{% block script %}

{% endblock script %}

story/templates/story/login.html
{% extends 'story/base.html' %}
{% load static %}

<!-- HEAD -->
{% block head %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://kit.fontawesome.com/f0cf88c973.js" crossorigin="anonymous"></script>
<link
    href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:100,200,300,400|Raleway:400,800|Indie+Flower|Ubuntu:400,500,600,300&display=swap"
    rel="stylesheet">
<link rel="stylesheet" href={% static 'story/story3.css' %}>
<link rel="stylesheet" href={% static 'story/profile.css' %}>
{% endblock head %}

{% block title %}
<title>Login</title>
{% endblock title %}


{% block body %}
<div class="dark">
    <div class="container profile__padd">
        <div class="">
            <h2 class="title__st3" style="width: fit-content; margin: auto auto 20px;">Login 👈</h2>
            <form class="site-form" action={% url 'story:login' %} method="post">
                {% csrf_token %}

                <div class ="input-field">
                    <i class ="material-icons prefix">face</i>
                    <label for="username">Username</label>
                </div>
                <input id="username" type="text" name="username">
                <div class ="input-field">
                    <i class ="material-icons prefix">lock</i>
                    <label for="password">Password</label>
                </div>
                <input id="password" type="password" name="password">

                {% for message in messages %}
                    <p style="color: red;">{{message}}</p>
                {% endfor %}
                <p style="margin-top: 30px;">or perhaps... you don't have an account yet? <a style="font-weight: 600; color: #b9ffd6;" href={% url 'story:register' %}>Register Here👋</a></p>
                <div class="center">
                    <input type="submit" value="Log In" class="reg__btn">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}


{% block script %}

{% endblock script %}

story/templates/story/navbar.html
{% load static %}
<nav id='navbar' class="navbar navbar-expand-lg navbar-light navbar__mod">

    <a class="navbar-brand" href={% url 'story:home' %}>
        <img src={% static 'story/logo/altopLogo.svg' %} alt="logo-navbar">
    </a>

    <button id="toogleNav" class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <ul class="navbar-nav social">



            <li class="nav-item">
                <a target="_blank" href='https://www.instagram.com/althof_rr/' class="social__link">
                    <img src={% static 'story/logo/instagram.svg' %} alt="">
                </a>
            </li>
            <li class="nav-item">
                <a target="_blank" href='https://www.linkedin.com/in/althofrr/' class="social__link">
                    <img src={% static 'story/logo/linkedin.svg' %} alt="">
                </a>
            </li>
            <li class="nav-item">
                <a target="_blank" href='https://github.com/althof3' class="social__link">
                    <img src={% static 'story/logo/github.svg' %} alt="">
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto text__navbar">
            {% with url_name=request.resolver_match.url_name%}

            <li class="nav-item">
                <a href={% url 'story:about' %}
                    class="nav_item base__font__viga fback {% if url_name == 'about' %}active-nav{% endif %}">About</a>
            </li>
            <li class="nav-item">
                <a href={% url 'story:course' %}
                    class="nav_item base__font__viga fback {% if url_name == 'course' %}active-nav{% endif %}">Courses</a>
            </li>
            <li class="nav-item">
                <a href={% url 'story:activity' %}
                    class="nav_item base__font__viga fback {% if url_name == 'activity' %}active-nav{% endif %}">Activity</a>
            </li>
            <li class="nav-item">
                <a href="" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false"
                    class="nav_item base__font__viga dropdown-toggle">more</a>
                <div style="
                    right: 200px;
                    width: fit-content;
                    left: unset;
                    background: #32303d;
                " class="shadow-lg dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                    <button class="dropdown-item" type="button">
                        <a 
                        href="{% url 'story:accordion' %}">
                            Accordion 🎵
                        </a>
                    </button>
                    <button class="dropdown-item" type="button">
                        <a 
                        href="{% url 'story:book' %}">
                            Book Catalogue 📚
                        </a>
                    </button>
                </div>
            </li>
            <li class="nav-item">
                <a href="" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false"
                class="nav_item base__font__viga dropdown-toggle">
                
                    {% if request.user.is_authenticated %}    
                    <img class="profile__img" src={{request.user.account.image}} alt="">
                    <span class="prof__name" >Hi, {{request.user.account.name}}</span>
                    {% else %}
                    <img class="profile__img" src={% static 'story/logo/user.svg' %} alt="">
                    {% endif %}
                        
                </a>
                <div style="
                    width: fit-content;
                    right: 40px;
                    left: unset;
                    background: #32303d;
                " class="shadow-lg dropdown-menu dropdown-menu-right dropdown-menu-lg-left">

                    
                    {% if request.user.is_authenticated %}
                        <button class="dropdown-item" type="button">
                            <a 
                            href="{% url 'story:dashboard' %}">
                                Dashboard 💨🛹
                            </a>
                        </button>
                        <button class="dropdown-item" type="button">
                            <a 
                            href="{% url 'story:logout' %}">
                                Logout 👉
                            </a>
                        </button>
                    {% else %}
                        <button class="dropdown-item" type="button">
                            <a 
                            href="{% url 'story:register' %}">
                                Register ✍
                            </a>
                        </button>
                        <button class="dropdown-item" type="button">
                            <a 
                            href="{% url 'story:login' %}">
                                Login 👈
                            </a>
                        </button>
                    {% endif %}
                        
                </div>
            </li>
            {%endwith%}
        </ul>
    </div>

</nav>

story/templates/story/register.html
{% extends 'story/base.html' %}
{% load static %}

<!-- HEAD -->
{% block head %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://kit.fontawesome.com/f0cf88c973.js" crossorigin="anonymous"></script>
<link
href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:100,200,300,400|Raleway:400,800|Indie+Flower|Ubuntu:400,500,600,300&display=swap"
rel="stylesheet">
<link rel="stylesheet" href={% static 'story/story3.css' %}>
<link rel="stylesheet" href={% static 'story/profile.css' %}>
{% endblock head %}

{% block title %}
<title>Register</title>
{% endblock title %}

{% block body %}
  <div class="dark">
  <div class="container profile__padd">
    <div class = "">
			<h2 class="title__st3" style="width: fit-content; margin: auto auto 20px;">Register ✍</h2>
			<form class="site-form" action={% url 'story:register' %} method="post">	
				{% csrf_token %}
				
				{% for field in form %}
					{{field.label}}
					{{field}}
				{% endfor %}
				{{ account_form }}

        {{form.errors}}
        <p style="margin-top: 30px;">already have an account? <a style="font-weight: 600; color: #b9ffd6;" href={% url 'story:login' %}>Login Here👋</a></p>
				<div class ="center">
					<input type="submit" value = "Sign Up" class = "reg__btn">
				</div>
			</form>
		</div>
  </div>
</div>
{% endblock body %}


{% block script %}

{% endblock script %}

story/templates/story/show_course.html
{% extends 'story/base.html' %}
{% load static %}

<!-- HEAD -->
{% block head %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href={% static 'story/show_course.css' %}>
<script src="https://kit.fontawesome.com/f0cf88c973.js" crossorigin="anonymous"></script>
<link
    href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:100,200,300,400|Raleway:400,800|Indie+Flower|Ubuntu:400,500,600,300&display=swap"
    rel="stylesheet">
{% endblock head %}

{% block title %}
<title>Altop | Course</title>
{% endblock title %}


{% block body %}
  <div class="show__course">
    <h2 style="margin: auto; max-width: max-content; margin-bottom: 40px;">List Mata Kuliah</h2>
    <a class="tambah__matkul" href={% url 'story:create_course' %}><i class="material-icons">add</i> Tambah Mata Kuliah</a>
    {% for matkul in matkuls %}
      <div class="matkul">
        <div class="matkul__desc">
          <a class="details" href={% url 'story:course_details' matkul.id %}>
            {{matkul.nama_mata_kuliah}} ({{matkul.jumlah_sks}} SKS)
          </a>
          <p class="dosen">{{matkul.dosen_pengajar}}</p>
        </div>
        <div class="matkul__detailBtn">
          
          <a class="delete" href={% url 'story:delete_course' matkul.id %}><i class="material-icons">delete_forever</i>Delete</a>
        </div>
      </div>
    {% endfor %}
      
  </div>
{% endblock body %}


{% block script %}
  
{% endblock script %}
  
  